/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * App API
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface RegisterDto {
  email: string;
  /** @minLength 6 */
  password: string;
  name?: string;
}
