/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * App API
 * The API description
 * OpenAPI spec version: 1.0
 */

export type UsersControllerGetProfile200 = { [key: string]: unknown };
