/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * App API
 * The API description
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


export const AppControllerGetHelloResponse = zod.string()


export const UsersControllerFindAllResponse = zod.unknown()


export const UsersControllerGetProfileResponse = zod.looseObject({

})


export const authControllerRegisterBodyPasswordMin = 6;



export const AuthControllerRegisterBody = zod.object({
  "email": zod.email(),
  "password": zod.string().min(authControllerRegisterBodyPasswordMin),
  "name": zod.string().optional()
})

export const AuthControllerRegisterResponse = zod.void()


export const AuthControllerLoginBody = zod.object({
  "email": zod.email(),
  "password": zod.string()
})

export const AuthControllerLoginResponse = zod.unknown()


